### ISSUE TITLE
Upload to device not working

### ISSUE THREAD

**Issue by 2er0** [sbcshop/RoundyFi#3]
When I follow the steps in the weather display example I end up with this error, when uploading to the RoundyFi. Everything else in the example seem to work fine.

```
Arduino: 1.8.19 (Linux), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Executable segment sizes:
ICACHE : 32768           - flash instruction cache 
IROM   : 286868          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 27485   / 32768 - code in IRAM          (IRAM_ATTR, ISRs...) 
DATA   : 1532  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 2000  ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 25944 )         - zeroed variables      (global, static) in RAM/HEAP 
Sketch uses 317885 bytes (30%) of program storage space. Maximum is 1044464 bytes.
Global variables use 29476 bytes (35%) of dynamic memory, leaving 52444 bytes for local variables. Maximum is 81920 bytes.
esptool.py v3.0
Serial port /dev/ttyACM0
Connecting........_____....._____....._____....._____....._____....._____.....____Traceback (most recent call last):
  File "/home/david/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/upload.py", line 66, in <module>
    esptool.main(cmdline)
  File "/home/david/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/esptool/esptool.py", line 3552, in main
    esp.connect(args.before, args.connect_attempts)
  File "/home/david/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/esptool/esptool.py", line 529, in connect
    raise FatalError('Failed to connect to %s: %s' % (self.CHIP_NAME, last_error))
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header

_
```

**Comment by MarPiSora** [comment]
sure that you set the right port?
On my Ubuntu RoundyFi device enumerates with (dmesg output):
`usb 1-2.1: cp210x converter now attached to ttyUSB0`

You may try to set the Serial port from /dev/ttyACM0 to e.g. port /dev/ttyUSB0

**Comment by 2er0** [comment]
Hmm... will have a look at that again, but I think I did not see an option to switch to `/dev/ttyUSB0`.

**Comment by 2er0** [comment]
A reboot of the PC and it worked - kernel update was the issue without rebooting - thanks for the tip with the `ttyUSB0`
